### ISSUE TITLE
CatGpt_0.3.1_x64_en-US  在哪加载live2D？

### ISSUE THREAD

**Issue by yslion** [Slebee/ChatGPT-live2d-Desktop#1]
![image](https://github.com/Slebee/ChatGPT-live2d-Desktop/assets/4454836/161a57d8-f859-4df9-af11-7f1015d311f0)

在哪加载live2D？

然后，聊天一直在请求状态 。 已经写了key了

**Comment by Slebee** [comment]
聊天窗口的爱心标记，点了之后出来的东西把你的live2d文件夹拖进去即可，没反应可以看看新版本的
